/**
 * Ticket Shop Items - Soul Cultivation App
 * Luxuries that users can "buy" for guilt-free downtime
 * Inflation Logic: Price increases by baseInflation% for each instance in inventory
 */

import { ItemTemplate } from '@/types/database';

export const TICKET_DATA: ItemTemplate[] = [
  {
    id: 'ticket-001',
    name: '15 Min Comic Reading',
    short_description: 'Quick escape.',
    full_description: 'A brief delve into a graphic world. Good for micro-breaks.',
    description: 'A brief delve into a graphic world. Good for micro-breaks.',
    cost_coins: 100,
    icon: 'BookOpen',
    category: 'tickets',
    cooldown_time: 24,
    base_inflation: 0.5, // 50%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-002',
    name: 'Eat Sweets',
    short_description: 'Sugar rush.',
    full_description: 'Indulge in refined sugars. Warning: High dopamine cost.',
    description: 'Indulge in refined sugars. Warning: High dopamine cost.',
    cost_coins: 250,
    icon: 'Candy',
    category: 'tickets',
    cooldown_time: 48,
    base_inflation: 1.0, // 100%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-003',
    name: '1 Hour Media',
    short_description: 'Digital immersion.',
    full_description: 'Youtube, Netflix, or Social Media. One hour of external projection.',
    description: 'Youtube, Netflix, or Social Media. One hour of external projection.',
    cost_coins: 400,
    icon: 'PlayCircle',
    category: 'tickets',
    cooldown_time: 24,
    base_inflation: 1.5, // 150%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-004',
    name: 'The Cloud Rain',
    short_description: 'Essence dispersion.',
    full_description: 'Sexual release. High cost to Jing/Vital essence. Use sparingly to maintain cultivation base.',
    description: 'Sexual release. High cost to Jing/Vital essence. Use sparingly to maintain cultivation base.',
    cost_coins: 1200,
    icon: 'CloudRain',
    category: 'tickets',
    cooldown_time: 168,
    base_inflation: 3.0, // 300%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-005',
    name: 'Order Takeout',
    short_description: 'Lazy nutrition.',
    full_description: 'Avoid cooking. Trade gold for convenience and processed calories.',
    description: 'Avoid cooking. Trade gold for convenience and processed calories.',
    cost_coins: 600,
    icon: 'Pizza',
    category: 'tickets',
    cooldown_time: 48,
    base_inflation: 1.0, // 100%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-006',
    name: 'Meet with Friend(s)',
    short_description: 'External Yang connection.',
    full_description: 'Socializing in a group. External energy exchange.',
    description: 'Socializing in a group. External energy exchange.',
    cost_coins: 200,
    icon: 'Users',
    category: 'tickets',
    cooldown_time: 12,
    base_inflation: 0.25, // 25%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-007',
    name: 'Visit Friends',
    short_description: 'Deep social bond.',
    full_description: 'One-on-one social connection. Strengthening external ties.',
    description: 'One-on-one social connection. Strengthening external ties.',
    cost_coins: 200,
    icon: 'Home',
    category: 'tickets',
    cooldown_time: 12,
    base_inflation: 0.25, // 25%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-008',
    name: 'Cinema / Theater',
    short_description: 'Grand spectacle.',
    full_description: 'Immersive external story. High-level disassociation.',
    description: 'Immersive external story. High-level disassociation.',
    cost_coins: 800,
    icon: 'Film',
    category: 'tickets',
    cooldown_time: 72,
    base_inflation: 0.5, // 50%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-009',
    name: 'Dine Outside',
    short_description: 'Culinary indulgence.',
    full_description: 'Full service meal. The ultimate luxury for a successful week of grind.',
    description: 'Full service meal. The ultimate luxury for a successful week of grind.',
    cost_coins: 1000,
    icon: 'Utensils',
    category: 'tickets',
    cooldown_time: 72,
    base_inflation: 0.75, // 75%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-010',
    name: 'Video Games (1 Hour)',
    short_description: 'Interactive escapism.',
    full_description: 'Active digital engagement. Drains focus but provides high stimulation.',
    description: 'Active digital engagement. Drains focus but provides high stimulation.',
    cost_coins: 250,
    icon: 'Gamepad',
    category: 'tickets',
    cooldown_time: 24,
    base_inflation: 1.0, // 100%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-011',
    name: 'Online Window Shopping',
    short_description: 'Mental clutter.',
    full_description: 'Browsing without intent. A high-cost distraction for the mind.',
    description: 'Browsing without intent. A high-cost distraction for the mind.',
    cost_coins: 200,
    icon: 'ShoppingBag',
    category: 'tickets',
    cooldown_time: 48,
    base_inflation: 1.5, // 150%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-012',
    name: 'Soda / Energy Drink',
    short_description: 'Liquid spark.',
    full_description: 'Caffeine and sugar hit. Temporary energy at the cost of long-term stability.',
    description: 'Caffeine and sugar hit. Temporary energy at the cost of long-term stability.',
    cost_coins: 150,
    icon: 'Coffee',
    category: 'tickets',
    cooldown_time: 24,
    base_inflation: 1.0, // 100%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-013',
    name: 'Fancy Coffee / Boba',
    short_description: 'Aesthetic consumption.',
    full_description: 'High-priced liquid dopamine. A social status vice.',
    description: 'High-priced liquid dopamine. A social status vice.',
    cost_coins: 250,
    icon: 'CupSoda',
    category: 'tickets',
    cooldown_time: 24,
    base_inflation: 0.75, // 75%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-014',
    name: 'Alcoholic Drink (1 Unit)',
    short_description: 'Numbing the senses.',
    full_description: 'Dulled awareness and inhibited presence. Lowers the frequency of the vessel.',
    description: 'Dulled awareness and inhibited presence. Lowers the frequency of the vessel.',
    cost_coins: 350,
    icon: 'Wine',
    category: 'tickets',
    cooldown_time: 24,
    base_inflation: 2.0, // 200%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-015',
    name: 'Vaping / Smoke Hit',
    short_description: 'Toxic breath.',
    full_description: 'Immediate nervous system hit. Highly damaging to the breath gate.',
    description: 'Immediate nervous system hit. Highly damaging to the breath gate.',
    cost_coins: 150,
    icon: 'Cigarette',
    category: 'tickets',
    cooldown_time: 24,
    base_inflation: 2.5, // 250%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'ticket-016',
    name: 'Gossip / Venting Session',
    short_description: 'Verbal energy leak.',
    full_description: 'Talking about others or complaining. Drains spiritual pressure and presence.',
    description: 'Talking about others or complaining. Drains spiritual pressure and presence.',
    cost_coins: 200,
    icon: 'MessageCircle',
    category: 'tickets',
    cooldown_time: 24,
    base_inflation: 1.0, // 100%
    effect_type: 'luxury',
    effect_value: 1,
    is_available: true,
    created_at: new Date().toISOString(),
  },
];
